type = "card"
title = "Education"
description = "Academic background."

[[items]]
title = "Southeast University"
subtitle = "Master's in Intelligent Science and Technology"
date = "2026-Present"

[[items]]
title = "Tiangong University"
subtitle = "Bachelor's in Software Engineering"
date = "2022-2026"
