type = "card"
title = "Education"
description = "Academic background."

[[items]]
title = "Southeast University"
subtitle = "Graduate Student in Intelligent Science and Technology"
date = "2026-Present"

[[items]]
title = "Tiangong University"
subtitle = "Software Engineering"
date = "2022-2026"
